model_hash = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        intermediate_hash = [40,197,24,176,239,154,121,53,108,167,249,212,219,132,28,154,123,170,2,145,65,36,223,10,40,188,102,168,199,102,42,183]
        result_hash = [150,116,106,75,250,45,48,188,11,241,175,47,13,4,158,221,198,183,237,16,218,123,209,152,169,57,37,35,128,61,114,50]
        weights = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        bias = [0,0,0,0,0,0,0,0,0,0]
        intermediate = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        